### ISSUE TITLE
Error integrating into nodejs app

### ISSUE THREAD

**Issue by ninapavlich** [DataDog/gae_datadog#11]
I amintegrating DataDog into a nodejs app that is running on Google App Engine.

I have followed the integration steps in the readme. When I deploy the app, I get the following error:
```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/datadog' must be set to 'auto' for runtime nodejs10.
error: exit status 1
```

This is what my app.yaml looks like:
```
service: api

runtime: nodejs10

env_variables:
  APP_ENV: dev
  DD_API_KEY: {{.DD_API_KEY}}
  DATADOG_API_KEY: {{.DD_API_KEY}}

handlers:
# Should probably be at the beginning of the list
# so it's not clobbered by a catchall route
- url: /datadog
  script: gae_datadog.datadog.app
```

I'm wondering if this integration only works for Python apps? If so, it would be helpful to note that in the ReadMe. Or if this should be possible, could more instruction be added to the ReadMe for this use case?
